# Generated by Django 4.1.5 on 2023-02-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
